### ISSUE TITLE
ENVO dropdowns are not available

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/nmdc-field-notes#176] opened 2024-09-16 18:24 UTC
### Bug summary

Envo terms are not available as dropdowns in app

### Bug details

I expected the ENVO categories/terms to be present as some sort of selectable list such as the options for growth facility or analysis/data type slots when I click the relevant slots (e.g., "broad scale environmental context"). I don't know the ENVO terms off the top of my head so I was not able to format them while out in the field and would have to do this later on the Submission Portal. As required fields, this prevents me from fully validating my metadata in-app.

### Steps to reproduce

In a sample, select broad-scale environmental context, local environmental context, or environmental medium. Pop-up is text-entry only, not a list of options.

### App version

0.1.0

### Device type

Apple

### Operating system version

iOS 17.6.1

**Comment by pkalita-lbl** [comment] 2024-09-16 18:26
Duplicate of https://github.com/microbiomedata/nmdc-field-notes/issues/143

**Comment by pkalita-lbl** [comment] 2024-09-16 21:14
I'm re-opening this one and marking #143 because this one is more likely to be found and understood by people searching for issues. But developers can look at #143 for technical details on what needs to be fixed.

**Closed** 2024-10-03 00:05 UTC
Labels: bug
