### ISSUE TITLE
In the sample attributes, when adding a value for "tissue growth media" I see a text box, but the example shows me a URL - I am not sure which to provide

### ISSUE THREAD

**Issue by sierra-moxon** [microbiomedata/nmdc-field-notes#188] opened 2024-09-25 16:51 UTC
### Bug summary

when adding data for "tissue growth media" I see a text box, but the example shows me a URL - I am not sure which to provide

### Bug details

The tissue culture growth media input field is a text box.  Because of this, I expect I should be able to describe in words what my tissue culture growth media is (tangential question - should this actually be a controlled vocabulary of terms instead of free text?)   I started entering text, but then, when consulting the example, I saw a URL -- does that mean it should be the URL for a paper that describes my materials and methods?

### Steps to reproduce

1. Launch app
2. create a study
3. create a sample
4. fill in the `tissue culture growth media` field

### Device type

Apple

### Operating system version

iOS 17.6.1

**Comment by mslarae13** [comment] 2024-11-11 18:32
Is this https://microbiomedata.github.io/submission-schema/tiss_cult_growth_med/ 
 ?

**Comment by pkalita-lbl** [comment] 2024-11-12 19:31
Yeah, my understanding is that we're talking about this slot: https://microbiomedata.github.io/submission-schema/tiss_cult_growth_med/

The description of the slot says "Description of plant tissue culture growth media used" which is fairly generic. The example for the slot is `https://link.springer.com/content/pdf/10.1007/BF02796489.pdf`. I believe that led to the confusion about what should be actually entered into the text box: a textual description? a URL where a description of the method can be found? In reality I believe either of those are acceptable. So maybe the answer here is that the slot's description should be expanded to explicitly state what type(s) of thing(s) we're looking for.

**Comment by pkalita-lbl** [comment] 2024-11-13 17:35
Since this is a schema issue I'm closing this issue in favor of an issue in the `nmdc-schema` repo

Duplicate of https://github.com/microbiomedata/nmdc-schema/issues/2267

**Closed by pkalita-lbl** 2024-11-13 17:35 UTC
Labels: bug, beta-feedback
